// src/lib/mockData.ts

export const mockProductos = [
  {
    id: 1,
    nombre: "Papa criolla",
    descripcion: "Papa fresca cultivada en los Andes.",
    precio: 3000,
    unidad: "kg",
    imagen: "/productos/default.jpg",
  },
  {
    id: 2,
    nombre: "Plátano maduro",
    descripcion: "Plátano dulce de cultivo orgánico.",
    precio: 2000,
    unidad: "kg",
    imagen: "/productos/default.jpg",
  },
  {
    id: 3,
    nombre: "Miel de abejas",
    descripcion: "100% natural, sin conservantes.",
    precio: 15000,
    unidad: "frasco (500ml)",
    imagen: "/productos/default.jpg",
  },
  {
    id: 4,
    nombre: "Café molido",
    descripcion: "Café artesanal de origen colombiano.",
    precio: 18000,
    unidad: "libra",
    imagen: "/productos/default.jpg",
  },
  {
    id: 5,
    nombre: "Yuca",
    descripcion: "Yuca recién cosechada, ideal para sopas o frituras.",
    precio: 2500,
    unidad: "kg",
    imagen: "/productos/default.jpg",
  },
  {
    id: 6,
    nombre: "Tomate chonto",
    descripcion: "Tomate jugoso y rojo, ideal para ensaladas.",
    precio: 2200,
    unidad: "kg",
    imagen: "/productos/default.jpg",
  },
  {
    id: 7,
    nombre: "Huevos campesinos",
    descripcion: "Huevos de gallina criolla, sin hormonas.",
    precio: 12000,
    unidad: "docena",
    imagen: "/productos/default.jpg",
  },
  {
    id: 8,
    nombre: "Aguacate Hass",
    descripcion: "Aguacate cremoso de excelente calidad.",
    precio: 3500,
    unidad: "unidad",
    imagen: "/productos/default.jpg",
  },
  {
    id: 9,
    nombre: "Panela en bloque",
    descripcion: "Panela artesanal sin refinar.",
    precio: 8000,
    unidad: "paquete (2 unidades)",
    imagen: "/productos/default.jpg",
  },
  {
    id: 10,
    nombre: "Queso campesino",
    descripcion: "Queso fresco producido en finca local.",
    precio: 10000,
    unidad: "lb",
    imagen: "/productos/default.jpg",
  },
  {
    id: 11,
    nombre: "Leche entera",
    descripcion: "Leche fresca recién ordeñada.",
    precio: 5000,
    unidad: "botella (1 litro)",
    imagen: "/productos/default.jpg",
  },
  {
    id: 12,
    nombre: "Maíz amarillo",
    descripcion: "Ideal para arepas o mazamorra.",
    precio: 4000,
    unidad: "kg",
    imagen: "/productos/default.jpg",
  },
  {
    id: 13,
    nombre: "Frijol cargamanto",
    descripcion: "Frijol de grano grande, excelente sabor.",
    precio: 7000,
    unidad: "libra",
    imagen: "/productos/default.jpg",
  },
  {
    id: 14,
    nombre: "Zanahoria",
    descripcion: "Zanahoria dulce y crocante.",
    precio: 1800,
    unidad: "kg",
    imagen: "/productos/default.jpg",
  },
  {
    id: 15,
    nombre: "Lulo",
    descripcion: "Fruta tropical ácida, ideal para jugos.",
    precio: 2500,
    unidad: "kg",
    imagen: "/productos/default.jpg",
  },
  {
    id: 16,
    nombre: "Guayaba",
    descripcion: "Fruta dulce para jugos o bocadillo.",
    precio: 2200,
    unidad: "kg",
    imagen: "/productos/default.jpg",
  },
  {
    id: 17,
    nombre: "Arequipe artesanal",
    descripcion: "Hecho en fogón de leña, cremoso y natural.",
    precio: 6000,
    unidad: "frasco (300g)",
    imagen: "/productos/default.jpg",
  },
  {
    id: 18,
    nombre: "Cebolla larga",
    descripcion: "Fresca, ideal para salsas y guisos.",
    precio: 1500,
    unidad: "manojo",
    imagen: "/productos/default.jpg",
  },
  {
    id: 19,
    nombre: "Limón mandarino",
    descripcion: "Cítrico suave, perfecto para bebidas.",
    precio: 1200,
    unidad: "kg",
    imagen: "/productos/default.jpg",
  },
  {
    id: 20,
    nombre: "Hierbabuena fresca",
    descripcion: "Ideal para aromáticas o cocina.",
    precio: 1000,
    unidad: "manojo",
    imagen: "/productos/default.jpg",
  },
];
